package com.steffanbecker.pedidos.database.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REQUEST_ITENS.
 */
public class Request_itens {

    private long item_id;
    private long request_id;
    private double item_price;
    private int item_quantity;

    public Request_itens() {
    }

    public Request_itens(long item_id, long request_id, double item_price, int item_quantity) {
        this.item_id = item_id;
        this.request_id = request_id;
        this.item_price = item_price;
        this.item_quantity = item_quantity;
    }

    public long getItem_id() {
        return item_id;
    }

    public void setItem_id(long item_id) {
        this.item_id = item_id;
    }

    public long getRequest_id() {
        return request_id;
    }

    public void setRequest_id(long request_id) {
        this.request_id = request_id;
    }

    public double getItem_price() {
        return item_price;
    }

    public void setItem_price(double item_price) {
        this.item_price = item_price;
    }

    public int getItem_quantity() {
        return item_quantity;
    }

    public void setItem_quantity(int item_quantity) {
        this.item_quantity = item_quantity;
    }

}
