package com.steffanbecker.pedidos.database.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORIES.
 */
public class Categories {

    private Long category_id;
    /** Not-null value. */
    private String category_name;
    private int category_active;

    public Categories() {
    }

    public Categories(Long category_id) {
        this.category_id = category_id;
    }

    public Categories(Long category_id, String category_name, int category_active) {
        this.category_id = category_id;
        this.category_name = category_name;
        this.category_active = category_active;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    /** Not-null value. */
    public String getCategory_name() {
        return category_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    public int getCategory_active() {
        return category_active;
    }

    public void setCategory_active(int category_active) {
        this.category_active = category_active;
    }

}
